### ISSUE TITLE
May I ask why you guys abandoned this container and can I help somehow? 

### ISSUE THREAD

**Issue by adrianocr** [linuxserver/docker-caddy#1]
Caddy is pretty sweet and I'm interested in running it in a container. I also love the containers you guys create. So I was ecstatic when I saw you guys had a caddy container but super let down when it said it wasn't available for public use and the last commit was 8 months ago :(

**Comment by p3lim** [comment]
Hi, I developed this image originally for distribution under the LinuxServer umbrella.
While it works (as far as I know, I'm running [the original version](https://github.com/p3lim/docker-caddy) on my servers), it never got any traction due to the parallel on-going effort of the [letsencrypt](https://github.com/linuxserver/docker-letsencrypt) image.

If you have any issues or suggestions for it, feel free to either/both post it here or/and on my original repo.

**Comment by CHBMB** [comment]
@p3lim I think the issue was we weren't prepared to release it unless someone was prepared to support it.  That aside we're having an overhaul of all the repos and ensuring they are licensed appropriately.  If you did wish to move forward with this then it would need a bit of work to make it multiarch, and you would need to be prepared to support it as the maintainer, especially as nobody on the team uses Caddy.

Can you let me know how you'd like to proceed please?
